In [1]:
import pandas as pd
data={'Tid':[1,2,3,4,5,6,7,8,9,10],
      'Refund':["yes","no","no","yes","no","no","yes","no","no","no"],
      'Marital Status':["single","married","single","married","divorced","married","divorced","single","married","single"],
      'Taxable income':["125k","100k","70k","120k","95k","60k","220k","85k","75k","90k"],
      'Cheat':["no","no","no","no","yes","no","no","yes","no","yes"]}
df=pd.DataFrame(data)
print(df)

   Tid Refund Marital Status Taxable income Cheat
0    1    yes         single           125k    no
1    2     no        married           100k    no
2    3     no         single            70k    no
3    4    yes        married           120k    no
4    5     no       divorced            95k   yes
5    6     no        married            60k    no
6    7    yes       divorced           220k    no
7    8     no         single            85k   yes
8    9     no        married            75k    no
9   10     no         single            90k   yes

In [2]:
print(df.loc[[0, 4, 7, 8]])

   Tid Refund Marital Status Taxable income Cheat
0    1    yes         single           125k    no
4    5     no       divorced            95k   yes
7    8     no         single            85k   yes
8    9     no        married            75k    no

In [3]:
print(df.loc[3:7])

   Tid Refund Marital Status Taxable income Cheat
3    4    yes        married           120k    no
4    5     no       divorced            95k   yes
5    6     no        married            60k    no
6    7    yes       divorced           220k    no
7    8     no         single            85k   yes

In [4]:
print(df.iloc[4:9, 2:5])

  Marital Status Taxable income Cheat
4       divorced            95k   yes
5        married            60k    no
6       divorced           220k    no
7         single            85k   yes
8        married            75k    no

In [5]:
print(df.iloc[:, 1:4])

  Refund Marital Status Taxable income
0    yes         single           125k
1     no        married           100k
2     no         single            70k
3    yes        married           120k
4     no       divorced            95k
5     no        married            60k
6    yes       divorced           220k
7     no         single            85k
8     no        married            75k
9     no         single            90k

In [6]:
import pandas as pd
df = pd.read_csv("Iris.csv")
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
pd.read_csv("Iris.csv")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [8]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
print(df.head(5))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
import pandas as pd
df = pd.read_csv("Iris.csv")
df = df.drop(index=4)
df = df.drop(df.columns[3], axis=1)

print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [1]:
import pandas as pd
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date":[
        "2020-03-15",
        "2017-07-19",
        "2013-06-01",
        "2021-02-10",
        "2010-11-25"
    ],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}
employees = pd.DataFrame(data)
employees.to_csv("employees.csv", index=False)
print(employees)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [2]:
print(employees.shape)

(5, 10)

In [3]:
print(employees.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes
None

In [4]:
print(employees.describe())

       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

In [5]:
print("First 5 rows:")
print(employees.head(5))

print("Last 3 rows:")
print(employees.tail(3))

First 5 rows:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
Last 3 rows:
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [6]:
print("Average Salary:", employees["Salary"].mean())
print("Total Bonus:", employees["Bonus"].sum())
print("Youngest Age:", employees["Age"].min())
print("Highest Rating:", employees["Rating"].max())

Average Salary: 60000.0
Total Bonus: 27500
Youngest Age: 28
Highest Rating: 4.7

In [7]:
sorted_employees = employees.sort_values(
    by="Salary",
    ascending=False
)
print(sorted_employees)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [8]:
def performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"
employees["Performance"] = employees["Rating"].apply(performance)
print(employees)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance
0   2020-03-15  Female   5000     4.5   Excellent
1   2017-07-19    Male   7000     4.0        Good
2   2013-06-01    Male   6000     3.8     Average
3   2021-02-10  Female   4500     4.7   Excellent
4   2010-11-25    Male   5000     3.5     Average

In [9]:
print(employees.isnull())

   Employee_ID   Name  Department    Age  Salary  Years_of_Experience  \
0        False  False       False  False   False                False
1        False  False       False  False   False                False
2        False  False       False  False   False                False
3        False  False       False  False   False                False
4        False  False       False  False   False                False

   Joining_Date  Gender  Bonus  Rating  Performance
0         False   False  False   False        False
1         False   False  False   False        False
2         False   False  False   False        False
3         False   False  False   False        False
4         False   False  False   False        False

In [10]:
employees.rename(
    columns={"Employee_ID": "ID"},
    inplace=True
)
print(employees)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance
0  Female   5000     4.5   Excellent
1    Male   7000     4.0        Good
2    Male   6000     3.8     Average
3  Female   4500     4.7   Excellent
4    Male   5000     3.5     Average

In [11]:
print(employees[employees["Years_of_Experience"] > 5])
print(employees[employees["Department"] == "IT"])

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average
4   Male   5000     3.5     Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average

In [12]:
employees["Tax"] = employees["Salary"] * 0.10
print(employees)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance     Tax
0  Female   5000     4.5   Excellent  5000.0
1    Male   7000     4.0        Good  7000.0
2    Male   6000     3.8     Average  6500.0
3  Female   4500     4.7   Excellent  5500.0
4    Male   5000     3.5     Average  6000.0

In [13]:
employees.to_csv("modified_employees.csv", index=False)
print("File saved successfully.")

File saved successfully.